variables:
  # REGISTRY: registry.example.com
  # REGISTRY_NAME: mumie
  # LATEST_VER: mumie/app:latest
  # MAJOR_VER: mumie/app:2
  KUBERNETES_CPU_REQUEST: 500m
  KUBERNETES_CPU_LIMIT: 1000m
  KUBERNETES_MEMORY_REQUEST: 512Mi
  KUBERNETES_MEMORY_LIMIT: 2048Mi

stages:
  - build
  # - test
  - push


include:
  - '/.gitlab-ci.docker.yml'
  - '/.gitlab-ci.kaniko.yml'


# before_script:
  # - echo "starting new job in $REGPATH"
  # - docker info
  #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


# jobs
build:rclone-mount:
  extends: .kaniko_build_template
  variables:
    ENV: rclone-mount

build:smb-mount:
  extends: .kaniko_build_template
  variables:
    ENV: smb-mount

build:sabnzbdvpn:
  extends: .kaniko_build_template
  variables:
    ENV: sabnzbdvpn

build:jdownloader:
  extends: .kaniko_build_template
  variables:
    ENV: jdownloader


#docker_build2:
#  stage: build
#  script:
#  - docker info
#  - docker build -t $LATEST_VER -t $MAJOR_VER .


# docker_test1:
#   stage: test
#   image: docker:latest
#   services:
#   - docker:dind
#   script:
#   - echo "finished"
#   # do some test
#   #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   only:
#     refs:
#       - master
#       - dev


# docker_push1:
#   stage: push
#   image: docker:latest
#   services:
#   - docker:dind
#   script:
#   - echo "manual job done"
#   # push image to registry
#   #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   only:
#     refs:
#       - master
#       - dev
#   when: manual

push:rclone-mount-latest:
  extends: .docker_push_template_latest
  variables:
    ENV: rclone-mount
  needs:
    - build:rclone-mount
push:rclone-mount-dev:
  extends: .docker_push_template_dev
  variables:
    ENV: rclone-mount
  needs:
    - build:rclone-mount

push:sabnzbdvpn-latest:
  extends: .docker_push_template_latest
  variables:
    ENV: sabnzbdvpn
  needs:
    - build:sabnzbdvpn
push:sabnzbdvpn-dev:
  extends: .docker_push_template_dev
  variables:
    ENV: sabnzbdvpn
  needs:
    - build:sabnzbdvpn
